from app.repositories.user_repository import UserRepository
from app.repositories.subject_repository import SubjectRepository
from app.repositories.course_repository import CourseRepository
from app.repositories.lesson_repository import LessonRepository
from app.repositories.quiz_repository import QuizRepository
from app.repositories.schedule_repository import ScheduleRepository
from app.repositories.note_repository import NoteRepository
from app.repositories.analytics_repository import AnalyticsRepository
